// frontend-vue/src/components/ui/LoadingSpinner.vue
<template>
  <div
    :class="['loading-spinner', `loading-spinner-${size}`, className]"
    :role="role"
    :aria-label="ariaLabel || $t('common.loading')"
    :aria-busy="true"
  >
    <span class="spinner-circle" aria-hidden="true"></span>
    <span v-if="showText" class="spinner-text">{{ text || $t('common.loading') }}</span>
  </div>
</template>

<script setup>
import { useI18n } from 'vue-i18n'

const props = defineProps({
  size: {
    type: String,
    default: 'md',
    validator: (value) => ['sm', 'md', 'lg'].includes(value)
  },
  text: {
    type: String,
    default: ''
  },
  showText: {
    type: Boolean,
    default: false
  },
  role: {
    type: String,
    default: 'status'
  },
  ariaLabel: {
    type: String,
    default: ''
  },
  className: {
    type: String,
    default: ''
  }
})

const { t } = useI18n()
</script>

<style scoped>
.loading-spinner {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.75rem;
}

.loading-spinner-sm {
  gap: 0.5rem;
}

.loading-spinner-lg {
  gap: 1rem;
}

.spinner-circle {
  display: inline-block;
  border: 3px solid rgba(59, 130, 246, 0.2);
  border-top-color: #3b82f6;
  border-radius: 50%;
  animation: spin 0.8s linear infinite;
}

.loading-spinner-sm .spinner-circle {
  width: 1rem;
  height: 1rem;
  border-width: 2px;
}

.loading-spinner-md .spinner-circle {
  width: 1.5rem;
  height: 1.5rem;
  border-width: 3px;
}

.loading-spinner-lg .spinner-circle {
  width: 2rem;
  height: 2rem;
  border-width: 4px;
}

.spinner-text {
  font-size: 0.875rem;
  color: #6b7280;
  font-weight: 500;
}

.dark .spinner-text {
  color: #9ca3af;
}

.loading-spinner-sm .spinner-text {
  font-size: 0.75rem;
}

.loading-spinner-lg .spinner-text {
  font-size: 1rem;
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}
</style>

// frontend/src/lib/components/ui/LoadingSpinner.svelte
<!--
  @component LoadingSpinner
  Reusable loading spinner with customizable message

  @prop {string} message - Loading message (default: "در حال بارگذاری...")
  @prop {string} size - Spinner size: 'sm' | 'md' | 'lg' (default: 'md')
-->

<script lang="ts">
  interface Props {
    message?: string;
    size?: 'sm' | 'md' | 'lg';
  }

  let { message = 'در حال بارگذاری...', size = 'md' }: Props = $props();

  // Size configurations
  let sizeConfig = $derived(() => {
    const configs = {
      sm: { container: '40px', border: '3px', fontSize: '0.875rem' },
      md: { container: '48px', border: '4px', fontSize: '1rem' },
      lg: { container: '64px', border: '5px', fontSize: '1.125rem' },
    };
    return configs[size];
  });
</script>

<div class="loading-spinner" role="status" aria-label={message}>
  <div
    class="spinner"
    style="--spinner-size: {sizeConfig.container}; --border-width: {sizeConfig.border}"
    aria-hidden="true"
  ></div>
  <p class="loading-message" style="--font-size: {sizeConfig.fontSize}">
    {message}
  </p>
</div>

<style>
  .loading-spinner {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 1rem;
    padding: 2rem;
    text-align: center;
  }

  .spinner {
    width: var(--spinner-size, 48px);
    height: var(--spinner-size, 48px);
    border: var(--border-width, 4px) solid var(--color-border);
    border-top: var(--border-width, 4px) solid var(--color-primary);
    border-radius: 50%;
    animation: spin 1s linear infinite;
  }

  .loading-message {
    margin: 0;
    color: var(--color-text-light);
    font-size: var(--font-size, 1rem);
  }

  @keyframes spin {
    0% {
      transform: rotate(0deg);
    }
    100% {
      transform: rotate(360deg);
    }
  }

  /* Reduce motion for accessibility */
  @media (prefers-reduced-motion: reduce) {
    .spinner {
      animation: none;
    }

    .spinner::after {
      content: '⏳';
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      font-size: calc(var(--spinner-size, 48px) * 0.6);
      animation: none;
    }
  }
</style>
